import "../App.css";
import { useState } from "react";

const GameTitle = () => {
  const [gameRunning, setGameRunning] = useState(false);
  const [attempt, setAttempt] = useState(0);
  const [level, setLevel] = useState(1);
  const [target, setTarget] = useState(0);
  const [score, setScore] = useState(0);

  const handleClick = () => {
    setGameRunning(true);
    setAttempt(Math.floor(Math.random() * 26));
    setTarget(Math.floor(Math.random() * 26) + 25);
    setLevel(localStorage.getItem("level"));
  };

    const handlePlay = () => {
        setScore(Math.floor(Math.random() * 5) + 1);
    }

  return (
    <div className="game-title">
      <h1>Game of Luck</h1>
      <h2>You are at Level: {level}</h2>
      <h2>Target: {target}</h2>
      <h2>Attempts Left: {attempt}</h2>
      {!gameRunning ? (
        <button className="button-29" onClick={handleClick}>
          Start Game
        </button>
      ) : (
        <button className="button-29" onClick={handlePlay}>
          Click to Generate Circles
        </button>
      )}
    
    {gameRunning && <h2>Circles Generated By this Click: {score}</h2>}
      
    </div>
  );
};

export default GameTitle;
